version: '3.8'

services:
  db:
    build: .
    image: postgress
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 
      POSTGRES_DB: meu_banco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
